### ISSUE TITLE
Signed Assembly

### ISSUE THREAD

**Issue by dvhub** [onovotny/BouncyCastle-PCL#3]
I'm interested in using your crypto.dll however it appears that it is not a signed dll.  Would it be possible for you to sign it in your NuGet package?

Also, I'm trying to open the GitHub solution with VS 2013.2 however I receive the following error message:

crypto.csproj : error  : The project file 'crypto' cannot be opened.

The project is targeting frameworks that are either not installed or are included as part of future updates to Visual Studio. See http://go.microsoft.com/fwlink/?LinkID=287985 for more information.

What dependency am I missing?

**Comment by jstedfast** [comment]
A signed assembly would really help me out as well since MimeKit and MailKit are both signed.

I've always known that strong naming assemblies did not improve security and that it was just about identifying the assembly, but I gave up trying to explain that to users demanding MimeKit and MailKit be strong-named, so I gave in and started strong-naming them.

It's really trivial to strong-name and I'm willing to send a PR if you'll accept it.

This would really help me out a lot because a PCL version of BouncyCastle is the last thing I need in order to support S/MIME, PGP, and DKIM for Windows Phone (and also it would let me stop maintaining my own fork of bc-csharp).

**Comment by onovotny** [comment]
Personal feelings about strong names aside, the biggest concern is the impact on the main BC project. @peterdettman has indicated that he's going to merge in this fork to bring PCL's into the main BC C# distribution https://github.com/bcgit/bc-csharp/issues/30. I don't believe BC currently has a strong name so adding one here would affect the PR.

If @peterdettman supports adding a strong name, then I'll accept it.

**Comment by peterdettman** [comment]
I believe we've always used strong names for BC releases. Feel free to add one here, I'll sort it all out in the merge.

**Comment by peterdettman** [comment]
Oh just to explain, the SN stuff is in the NAnt build but file not in git, probably because I mistook it for a security feature originally.

**Comment by onovotny** [comment]
@peterdettman I'll be happy to add it here; I didn't see the snk file checked in. Microsoft is recommending that OSS projects check in the snk file to source control.

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md
and https://msdn.microsoft.com/en-us/library/wd40t7ad.aspx both say so...

Reason it's ok is because it's for assembly identity not security. By that same token, .snk should prob be removed from the .gitignores too.

If you can check in the snk, I'll use it and sign this one with it.
